name: Browser Extension Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  manifestinfo:
    name: Get Extension Info
    runs-on: ubuntu-24.04
    outputs: 
      version: ${{ steps.ExtensionVersion.outputs.version }}
      name: ${{ steps.ExtensionName.outputs.name }}
      sizes: ${{ steps.IconSizes.outputs.sizes }}
    
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: ExtensionVersion
        name: Get Extension Version
        run: |
          value=$(jq -r .version manifest.json)
          echo "version=$value" >> $GITHUB_OUTPUT

      - id: ExtensionName
        name: Get Extension Name
        run: |
          value=$(jq -r .name manifest.json | sed 's/ /-/')
          echo "name=$value" >> $GITHUB_OUTPUT

      - id: IconSizes
        name: Get Icon Sizes
        run: |
          sizes=$(jq -r '.icons | keys | map(tonumber) | sort | join(" ")' manifest.json)
          echo "sizes=$sizes" >> $GITHUB_OUTPUT

  build:
    name: Build Extension
    runs-on: ubuntu-20.04
    needs: manifestinfo
    steps:
    - id: checkout
      uses: actions/checkout@v4

    - id: icons
      name: Create Icon Set
      run: |
        imagesizes="${{needs.manifestinfo.outputs.sizes}}"
        for i in $imagesizes; do 
          if [[ $i -eq 128 ]]; then
            echo "original size, nothing to do"
            continue
          fi
          echo "creating ${i}x${i} icon"
          convert icon-128.png -resize ${i}x${i} icon-${i}.png
        done
      working-directory: ./icons

    - id: build
      name: Collect Extension Files
      run: |
        mkdir export
        cd export
        cp ../icons/*.png .
        cp ../*.js* .
        cp ../*.html .

    - id: publish-artifact
      name: Artifact Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{needs.manifestinfo.outputs.name}}-${{needs.manifestinfo.outputs.version}}
        path: export/
